solver:
  type: ilqr
  ipopt.linear_solver: ma57
  ilqr.constr_viol_tol: 1e-9
  ipopt.tol: 1e-9
  ipopt.constr_viol_tol: 1e-9
#  ipopt.hessian_approximation: exact
  ilqr.verbose: false
  ilqr.codegen_enabled: true
  ilqr.codegen_workdir: /tmp/miao
  ilqr.enable_gn: true
  ipopt.print_level: 5
  ipopt.suppress_all_output: 'yes'
  ipopt.sb: 'yes'
  print_time: 0

constraints:
  - foot_contact_l
  - foot_contact_r

costs:
  - base_xy
  - base_z
  - joint_posture
  - joint_posture_hips
  - joint_posture_knee
#  - joint_posture_upper_body
  - base_roll_orientation
  - base_pitch_orientation
  - base_yaw_orientation
  - foot_rot_l
  - foot_rot_r
  - foot_z_l
  - foot_z_r
  - velocity_regularization
  - acceleration_regularization
  - f_left_regularization_0
  - f_left_regularization_1
  - f_left_regularization_2
  - f_left_regularization_3
  - f_right_regularization_0
  - f_right_regularization_1
  - f_right_regularization_2
  - f_right_regularization_3
#  - zero_vel_xy_r_sole
#  - zero_vel_xy_l_sole
#  - joint_regularization #, foot_z_l_sole, foot_z_r_sole] # com_height

.define:
    - &w_base_z 0.
    - &w_base_ori_r 10.
    - &w_base_ori_p 10.
    - &w_base_ori_y 100.
    - &w_base_xy 50.
    - &w_contact_z 1000.
    - &w_postural 1.
    - &w_postural_hips 100.
    - &w_postural_knee 0.1
    - &w_postural_ub 1.
    - &w_v 2.
    - &w_a 1e-3
    - &w_f 2e-2
    - &w_sole_rot 100.

base_xy:
  type: Cartesian
  distal_link: torso_link
  indices: [0, 1]
  nodes: ${[N]}
  weight: *w_base_xy

base_z:
  type: Cartesian
  distal_link: torso_link
  indices: [2]
  nodes: all
  weight: *w_base_z

base_roll_orientation:
  type: Cartesian
  distal_link: torso_link
  indices: [3, 4]
  nodes: all
  weight: *w_base_ori_r

base_pitch_orientation:
  type: Cartesian
  distal_link: torso_link
  indices: [3, 4]
  nodes: all
  weight: *w_base_ori_p

base_yaw_orientation:
  type: Cartesian
  distal_link: torso_link
  indices: [5]
  nodes: all
  weight: *w_base_ori_y

foot_rot_l:
  type: Cartesian
  distal_link: l_sole
  indices: [3, 4, 5]
  nodes: all
#  cartesian_type: position
  weight: *w_sole_rot

foot_rot_r:
  type: Cartesian
  distal_link: r_sole
  indices: [3, 4, 5]
  nodes: all
#  cartesian_type: position
  weight: *w_sole_rot

# ===============================

foot_interaction_l:
  type: VertexForce
  frame: l_sole
  fn_min: 10.0
  friction_coeff: 0.5
  enable_fc: true
  vertex_frames:
    - l_sole_lower_left_link
    - l_sole_upper_left_link
    - l_sole_lower_right_link
    - l_sole_upper_right_link

foot_zero_velocity_l:
  type: Cartesian
  distal_link: l_sole
  indices: [0, 1, 2, 5]
  cartesian_type: velocity

foot_interaction_r:
  type: VertexForce
  frame: r_sole
  fn_min: 10.0
  friction_coeff: 0.5
  enable_fc: true
  vertex_frames:
    - r_sole_lower_left_link
    - r_sole_upper_left_link
    - r_sole_lower_right_link
    - r_sole_upper_right_link

foot_zero_velocity_r:
  type: Cartesian
  distal_link: r_sole
  indices: [0, 1, 2, 5]
  cartesian_type: velocity

foot_contact_l:
  type: Contact
  subtask: [foot_interaction_l, foot_zero_velocity_l]

foot_contact_r:
  type: Contact
  subtask: [foot_interaction_r, foot_zero_velocity_r]

# ==================================

joint_posture:
  type: Postural
  weight: *w_postural
#  indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  indices: ['left_hip_pitch_joint', 'left_hip_yaw_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
            'right_hip_pitch_joint', 'right_hip_roll_joint', 'right_hip_yaw_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint',
            'waist_yaw_joint', 'waist_roll_joint', 'waist_pitch_joint',
            'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint', 'left_wrist_roll_joint', 'left_wrist_pitch_joint', 'left_wrist_yaw_joint',
            'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint', 'right_wrist_roll_joint', 'right_wrist_pitch_joint', 'right_wrist_yaw_joint']
  nodes: all

joint_posture_knee:
  type: Postural
  weight: *w_postural_knee
#  indices: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  indices: ['right_knee_joint', 'left_knee_joint']
  nodes: all

joint_posture_hips:
  type: Postural
  weight: *w_postural_hips
  indices: ['left_hip_roll_joint', 'right_hip_roll_joint']
  nodes: all

#joint_posture_upper_body:
#  type: Postural
#  weight: *w_postural_ub
#  indices: [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
#  nodes: all

velocity_regularization:
  type: Regularization
  variable_name: v
  nodes: all
  weight: *w_v

acceleration_regularization:
  type: Regularization
  variable_name: a
  nodes: all
  weight: *w_a # 0.01

f_left_regularization_0:
  type: Regularization
  variable_name: f_l_sole_lower_left_link
  nodes: all
  weight: *w_f

f_left_regularization_1:
  type: Regularization
  variable_name: f_l_sole_lower_right_link
  nodes: all
  weight: *w_f

f_left_regularization_2:
  type: Regularization
  variable_name: f_l_sole_upper_left_link
  nodes: all
  weight: *w_f

f_left_regularization_3:
  type: Regularization
  variable_name: f_l_sole_upper_right_link
  nodes: all
  weight: *w_f

f_right_regularization_0:
  type: Regularization
  variable_name: f_r_sole_lower_left_link
  nodes: all
  weight: *w_f

f_right_regularization_1:
  type: Regularization
  variable_name: f_r_sole_lower_right_link
  nodes: all
  weight: *w_f

f_right_regularization_2:
  type: Regularization
  variable_name: f_r_sole_upper_left_link
  nodes: all
  weight: *w_f

f_right_regularization_3:
  type: Regularization
  variable_name: f_r_sole_upper_right_link
  nodes: all
  weight: *w_f

foot_z_l:
  type: Cartesian
  distal_link: l_sole
  indices: [2]
  cartesian_type: position
  weight: *w_contact_z

foot_z_r:
  type: Cartesian
  distal_link: r_sole
  indices: [2]
  cartesian_type: position
  weight: *w_contact_z

foot_zero_vel_xy_l:
  type: Cartesian
  distal_link: l_sole
  indices: [0, 1]
  cartesian_type: velocity
  weight: *w_contact_z

foot_zero_vel_xy_r:
  type: Cartesian
  distal_link: r_sole
  indices: [0, 1]
  cartesian_type: velocity
  weight: *w_contact_z

#foot_xy_l_sole:
#  type: Cartesian
#  distal_link: l_sole
#  indices: [0, 1]
#  cartesian_type: position

#foot_xy_r_sole:
#  type: Cartesian
#  distal_link: r_sole
#  indices: [0, 1]
#  cartesian_type: position
